import type { Metadata } from 'next';
import type { CSSProperties, ReactNode } from 'react';
import { defaultLocale } from '../i18n';
import './globals.css';

const fontVariables = {
  className: 'font-sans',
  style: {
    '--font-geist-sans':
      "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    '--font-geist-mono':
      "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
  } as CSSProperties,
};

export const metadata: Metadata = {
  title: 'Appversal',
  description: 'Generated by create next app',
  icons: {
    icon: '/appversal-logo-short.png',
  },
};

type RootLayoutProps = Readonly<{ children: ReactNode }>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang={defaultLocale} suppressHydrationWarning>
      <head>
        <link rel='icon' href='/appversal-logo-short.png' />
      </head>
      <body
        className={`${fontVariables.className} antialiased`}
        style={fontVariables.style}
      >
        {children}
      </body>
    </html>
  );
}
