import type { Metadata } from "next";
import "./globals.css";

// Temporarily using CSS variables for fonts due to build environment restrictions
// Google Fonts (Geist and Geist Mono) will be loaded via CSS or at runtime
const fontVariables = {
  className: "font-sans",
  style: {
    "--font-geist-sans": "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    "--font-geist-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
  } as React.CSSProperties,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontVariables.className} antialiased`}
        style={fontVariables.style}
      >
        {children}
      </body>
    </html>
  );
}
